(cl:in-package vector_slam_msgs-msg)
(cl:export '(TIMESTAMP-VAL
          TIMESTAMP
          ROBOTLOCX-VAL
          ROBOTLOCX
          ROBOTLOCY-VAL
          ROBOTLOCY
          ROBOTANGLE-VAL
          ROBOTANGLE
          WINDOWSIZE-VAL
          WINDOWSIZE
          LINES_P1X-VAL
          LINES_P1X
          LINES_P1Y-VAL
          LINES_P1Y
          LINES_P2X-VAL
          LINES_P2X
          LINES_P2Y-VAL
          LINES_P2Y
          LINES_COL-VAL
          LINES_COL
          POINTS_X-VAL
          POINTS_X
          POINTS_Y-VAL
          POINTS_Y
          POINTS_COL-VAL
          POINTS_COL
          CIRCLES_X-VAL
          CIRCLES_X
          CIRCLES_Y-VAL
          CIRCLES_Y
          CIRCLES_COL-VAL
          CIRCLES_COL
          TEXT_X-VAL
          TEXT_X
          TEXT_Y-VAL
          TEXT_Y
          TEXT_COL-VAL
          TEXT_COL
          TEXT-VAL
          TEXT
          TEXT_HEIGHT-VAL
          TEXT_HEIGHT
          TEXT_IN_WINDOW_COORDS-VAL
          TEXT_IN_WINDOW_COORDS
))