(cl:defpackage vector_slam_msgs-srv
  (:use )
  (:export
   "LOCALIZATIONGUICAPTURESRV"
   "<LOCALIZATIONGUICAPTURESRV-REQUEST>"
   "LOCALIZATIONGUICAPTURESRV-REQUEST"
   "<LOCALIZATIONGUICAPTURESRV-RESPONSE>"
   "LOCALIZATIONGUICAPTURESRV-RESPONSE"
   "COBOTLOCALIZATIONSRV"
   "<COBOTLOCALIZATIONSRV-REQUEST>"
   "COBOTLOCALIZATIONSRV-REQUEST"
   "<COBOTLOCALIZATIONSRV-RESPONSE>"
   "COBOTLOCALIZATIONSRV-RESPONSE"
   "COBOTREMOTEINTERFACESRV"
   "<COBOTREMOTEINTERFACESRV-REQUEST>"
   "COBOTREMOTEINTERFACESRV-REQUEST"
   "<COBOTREMOTEINTERFACESRV-RESPONSE>"
   "COBOTREMOTEINTERFACESRV-RESPONSE"
  ))

