(cl:in-package vector_slam_msgs-srv)
(cl:export '(DRIVE_X-VAL
          DRIVE_X
          DRIVE_Y-VAL
          DRIVE_Y
          DRIVE_R-VAL
          DRIVE_R
          MAX_VEL_TRANS-VAL
          MAX_VEL_TRANS
          MAX_VEL_ROT-VAL
          MAX_VEL_ROT
          COMMAND_NUM-VAL
          COMMAND_NUM
          COMMAND_TYPE-VAL
          COMMAND_TYPE
          LOC_X-VAL
          LOC_X
          LOC_Y-VAL
          LOC_Y
          ORIENTATION-VAL
          ORIENTATION
          DISTANCE_TOLERANCE-VAL
          DISTANCE_TOLERANCE
          ANGLE_TOLERANCE-VAL
          ANGLE_TOLERANCE
          MAP-VAL
          MAP
          LOC_X-VAL
          LOC_X
          LOC_Y-VAL
          LOC_Y
          ORIENTATION-VAL
          ORIENTATION
          PARTICLES_X-VAL
          PARTICLES_X
          PARTICLES_Y-VAL
          PARTICLES_Y
          PARTICLES_WEIGHT-VAL
          PARTICLES_WEIGHT
          LOCATIONS_WEIGHT-VAL
          LOCATIONS_WEIGHT
          ERR_CODE-VAL
          ERR_CODE
))