(cl:defpackage visual_feature_server-srv
  (:use )
  (:export
   "CONVERT2DPOINT"
   "<CONVERT2DPOINT-REQUEST>"
   "CONVERT2DPOINT-REQUEST"
   "<CONVERT2DPOINT-RESPONSE>"
   "CONVERT2DPOINT-RESPONSE"
   "PICKLESRV"
   "<PICKLESRV-REQUEST>"
   "PICKLESRV-REQUEST"
   "<PICKLESRV-RESPONSE>"
   "PICKLESRV-RESPONSE"
  ))

