(cl:in-package vector_slam_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          TIMESTAMP-VAL
          TIMESTAMP
          LOC_X-VAL
          LOC_X
          LOC_Y-VAL
          LOC_Y
          ORIENTATION-VAL
          ORIENTATION
          PARTICLES_X-VAL
          PARTICLES_X
          PARTICLES_Y-VAL
          PARTICLES_Y
          PARTICLES_WEIGHT-VAL
          PARTICLES_WEIGHT
          LOCATIONS_WEIGHT-VAL
          LOCATIONS_WEIGHT
          CURRENTNAVCOMMAND-VAL
          CURRENTNAVCOMMAND
          OBSAVDIR_X-VAL
          OBSAVDIR_X
          OBSAVDIR_Y-VAL
          OBSAVDIR_Y
          PATHBLOCKED-VAL
          PATHBLOCKED
          BATTERYVOLTAGE-VAL
          BATTERYVOLTAGE
          EMERGENCYSTOP-VAL
          EMERGENCYSTOP
          COBOTMODE-VAL
          COBOTMODE
          CURRENTCOMMAND-VAL
          CURRENTCOMMAND
          NAVCOMPLETE-VAL
          NAVCOMPLETE
          CURRENTEDGE-VAL
          CURRENTEDGE
          EDGEPROGRESS-VAL
          EDGEPROGRESS
          EDGEREMAINING-VAL
          EDGEREMAINING
          EDGENAVDURATION-VAL
          EDGENAVDURATION
          PATHPLAN_X-VAL
          PATHPLAN_X
          PATHPLAN_Y-VAL
          PATHPLAN_Y
))